### ISSUE TITLE
Probleme when adding répository

### ISSUE THREAD

**Issue by moi22441** [frazrepo/hassio-freebox#1]
I have this issue when i want to add your repository :

20-01-01 18:32:31 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/7dac9029/freebox-assistant-plugin/config.json: required key not provided @ data['arch']. Got None

Thanks for your help

**Comment by Edmond76** [comment]
Everytime HA restart/start you have to autorized, on your Freebox front panel, the plugin. Try this: restart the plugin, wait few second then you'll see, on your Freebox, a message instead of the hour, then use right arrow to autorized.

A chaque fois que Home Assistant démarre ou est redémarré, tu dois autorisé le plugin sur ta Freebox. Redémarre le plugin depuis Home Assistant, attends quelques secondes et tu verras un message sur la Freebox Server au lieu de l'heure. Appuie sur la flèche de droite pour autoriser le plugin.

Good Luck
Ed

**Comment by frazrepo** [comment]
I updated the plugin to be compatible with the latest version of HA (0.110.1).
It should be fine now.
